http:
  middlewares:
    vpn-whitelist:
      ipAllowList:
        sourceRange:
          - "10.99.0.0/16"
          - "10.0.0.0/12"

    authorized-owntrack-users:
      basicAuth:
        usersFile: "/authorized-owntrack-users"