networks:
  auth_backend:
    driver: bridge
  public:
    driver: bridge

volumes:
  postgres-data:

services:
  watchtower:
    container_name: auth_watchtower
    image: nickfedor/watchtower
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL:?Watchtower url required}
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgresql:
    container_name: auth_postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: authentik
    networks:
      - auth_backend
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: auth_server
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - auth_backend
      - public
    env_file:
      - .env
      - .env_authentic
    environment:
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:?AUTHENTIK_TAG_required}
#    ports:
#      - 9443:9443
    restart: unless-stopped
    volumes:
      - ./authentik/data:/data
      - ./authentik/templates:/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.ffw-it.de`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.service=auth"
      - "traefik.http.services.auth.loadbalancer.server.url=http://auth_server:9000"

  worker:
    container_name: auth_worker
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - auth_backend
    env_file:
      - .env
      - .env_authentic
    environment:
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:?AUTHENTIK_TAG_required}
    restart: unless-stopped
    user: root
    volumes:
      - ./authentik/data:/data
      - ./authentik/certs:/certs
      - ./authentik/templates:/templates